### ISSUE TITLE
KeyError on missing grain

### ISSUE THREAD

**Issue by mchugh19** [carlpett/salt-vault#17]
Just ran into the previous error:
```
# salt-run vault.show_policies ip-10-241-208-27.ec2.internal
Exception occurred in runner vault.show_policies: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/var/cache/salt/master/extmods/runners/vault.py", line 50, in show_policies
    return _get_policies(minion_id, config)
  File "/var/cache/salt/master/extmods/runners/vault.py", line 77, in _get_policies
    for expanded_pattern in _expand_pattern_lists(pattern, **mappings):
  File "/var/cache/salt/master/extmods/runners/vault.py", line 113, in _expand_pattern_lists
    (value, _) = f.get_field(field_name, None, mappings)
  File "/usr/lib64/python2.7/string.py", line 640, in get_field
    obj = obj[i]
KeyError: 'Environment'
```

**Comment by carlpett** [comment]
Hm, I don't think you're running the latest code. I merged the try/except code yesterday evening, so you might need to pull again. The line numbers in your stack trace don't match the code in master, at least.

**Comment by mchugh19** [comment]
Right you are. Current version looks good. Thanks!
