### ISSUE TITLE
Exception in state module

### ISSUE THREAD

**Issue by zerthimon** [carlpett/salt-vault#18]
I'm trying to set up salt-vault and getting the following exceptoins

When doing read_secret:
```
[ERROR   ] Failed to get token from master! An error was returned: Missing ']' in format string
[ERROR   ] Failed to read secret! CommandExecutionError: {'error': "Missing ']' in format string"}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/vault.py", line 48, in read_secret
    raise salt.exceptions.CommandExecutionError(e)
CommandExecutionError: {'error': "Missing ']' in format string"}
Error running 'vault.read_secret': {'error': "Missing ']' in format string"}
```

When doing list_secrets:
```
[ERROR   ] Failed to get token from master! An error was returned: Missing ']' in format string
[ERROR   ] Failed to list secrets! CommandExecutionError: {'error': "Missing ']' in format string"}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 197, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/vault.py", line 115, in list_secrets
    raise salt.exceptions.CommandExecutionError(e)
CommandExecutionError: {'error': "Missing ']' in format string"}
Error running 'vault.list_secrets': {'error': "Missing ']' in format string"}
```

What I'm doing wrong ?

**Comment by carlpett** [comment]
Could you share the configuration section `policies`? I suspect that there might be something amiss there.

**Comment by zerthimon** [comment]
@carlpett yep, I used `{grains[ec2_tags:Environment]}`
changed to `{grains[ec2_tags][Environment]}` and that fixed it ..
Thanks

**Comment by carlpett** [comment]
Great!
